package com.campuscompanion.cc.client.utility;

public class Event {
    private int eventID;
    private String club;
    private String name;
    private String date;
    private String location;
    private int rsvpCount;

    // Constructor for creating a new event with an auto-generated EventID (EventID
    // can be 0)
    public Event(int eventID, String club, String name, String date, String location, int rsvpCount) {
        this.eventID = eventID; // EventID will be auto-generated by the database
        this.club = club;
        this.name = name;
        this.date = date; // Store date as String
        this.location = location;
        this.rsvpCount = rsvpCount;
    }

    public Event(String club, String name, String date, String location, int rsvpCount) {
        this.eventID = 0; // EventID will be auto-generated by the database
        this.club = club;
        this.name = name;
        this.date = date; // Store date as String
        this.location = location;
        this.rsvpCount = rsvpCount;
    }

    // Default constructor for other uses (like fetching from DB)
    public Event() {
    }

    // Getters and setters
    public int getEventID() {
        return eventID;
    }

    public void setEventID(int eventID) {
        this.eventID = eventID;
    }

    public String getClub() {
        return club;
    }

    public void setClub(String club) {
        this.club = club;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDate() {
        return date; // Return date as String
    }

    public void setDate(String date) {
        this.date = date; // Set date as String
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public int getRSVPCount() {
        return rsvpCount;
    }

    public void setRSVPCount(int rsvpCount) {
        this.rsvpCount = rsvpCount;
    }
}
